---
galaxy_info:
  author: yash
  description: Install and configure RabbitMQ on Debian/Ubuntu only
  company: ""
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

