---
galaxy_info:
  author: yash
  description: Install Apache Maven on Debian/Ubuntu
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

