---
- name: Install Memcached
  apt:
    name: memcached
    state: present
    update_cache: yes

- name: Ensure Memcached is running
  service:
    name: memcached
    state: started
    enabled: yes

